### ISSUE TITLE
有docker版本的吗我使用的是unraid系统

### ISSUE THREAD

**Issue by a13087635768** [koolshare/ddnsto#104]
有docker版本的吗我使用的是unraid系统 我想用docker来部署一套方案 其他安装方式有点麻烦

**Comment by jannson** [comment]
暂时没有，没精力。大版本开发中，后续边缘的插件都会有的。

**Comment by jannson** [comment]
https://github.com/koolshare/linkease

2.0 版本 docker 开发中，请等等
