### ISSUE TITLE
Docker安装怎么设置token啊？

### ISSUE THREAD

**Issue by feiyihx** [koolshare/ddnsto#106]
你好，我是用旧笔记本装的PVE底层系统，然后在OMV虚拟机里用docker的GUI安装的。
安装非常简单，直接用80x86/filebrowser:latest拉取镜像然后设置端口和config还有data目录就行。
本地运行完全没有问题。
但是请问用docker安装的怎么设置令牌呢？是在docker的环境变量里面增加什么变量呢？谢谢！
另外，请问token其实是有什么用啊？再次感谢！

**Comment by jannson** [comment]
命令行有一个 --help 里面有帮助。-u xxx 就可以了。

**Comment by feiyihx** [comment]
hi，你的意思是直接在部署docker的时候在环境变量里面添加一个变量u，值为我的token？
