### ISSUE TITLE
ios端易有云看不到其他设备

### ISSUE THREAD

**Issue by hohoho323** [koolshare/ddnsto#108]
我在网页上可以看到其他设备包括iphone，但是在ios端不能看到其他设备。

**Comment by 953786940** [comment]
附议 同样的情况

**Comment by jianwong0514** [comment]
没有回答么

**Comment by 953786940** [comment]
作者被隔离 等待更新



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jianwong0514 <notifications@github.com&gt;
发送时间: 2020年2月14日 22:59
收件人: koolshare/ddnsto <ddnsto@noreply.github.com&gt;
抄送: 953786940 <953786940@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[koolshare/ddnsto] ios端易有云看不到其他设备 (#108)




没有回答么

**Comment by jannson** [comment]
等我备案（突然备案消失，两年前用一个老家兄弟的名字备的案），或者等 iOS 的过年去湖北的兄弟回归。第一时间我就在首页写了说明，非常不好意思。

**Comment by jannson** [comment]
开发者还在湖北，但是用手头旧代码重新上线可以用了，可能会有一些老bug重新出现，请见谅.
