### ISSUE TITLE
易有云同步报错

### ISSUE THREAD

**Issue by jnhch** [koolshare/ddnsto#111]
![R)P8H)2}MEJ)M}K(~82X$GY](https://user-images.githubusercontent.com/61749761/76083232-135af180-5fe8-11ea-9ea9-cd6fc5df152a.png)
你好，易有云复制移动文件一切正常，选择同步就报错，请问是什么原因？
系统梅林380.70_0-X7.9.1
硬件网件R6300V2

**Comment by jannson** [comment]
路由器暂时不支持双向同步，等后面会支持单向同步。
