### ISSUE TITLE
路由器端不能设定共享目录

### ISSUE THREAD

**Issue by HsiYaTung** [koolshare/ddnsto#113]
路由器梅林固件上无法设定共享目录。
按照说明双击后弹出如下对话框:
![图片](https://user-images.githubusercontent.com/13701247/76145262-11b22c00-60c3-11ea-9c53-b17da16db455.png)

**Comment by sadoneli** [comment]
只有插入USB储存设备后，双击才会弹出目录选择
如果要共享路由器自己的目录，请直接输入目录的路径，如`/jffs` `/root`等

**Comment by jannson** [comment]
易有云 2.0 解决了这个问题。https://github.com/koolshare/linkease
