### ISSUE TITLE
希望DDNSto能进行适当收费

### ISSUE THREAD

**Issue by chacha20** [koolshare/ddnsto#115]
我知道作者到处找服务器的确不容易，维护代码也不容易，希望DDNSto能进行适当收费，我是很喜欢这个应用的，也希望能一直用下去。如果受限于开源协议的话，我想应该可以提供一些赞助方式或者以提供收费服务的方式来获取一些经费。

**Comment by jannson** [comment]
感谢支持。代码全部自己写的，没有受限于开源协议。

我们团队在全力开发易有云 2.0 ，等我们有精力了会把 DDNSTO 再好好升级一次，到时候会考虑收费。

DDNSTO 虽然中间出现一些故障，主要是服务器，备案，证书等原因，我们也一直在坚持让它继续保持工作。不管收不收费，看得见的两年时间内它会服务下去。
