### ISSUE TITLE
iis,https自签名证书，内网可访问，外网不行。

### ISSUE THREAD

**Issue by billizpl** [koolshare/ddnsto#116]
iis,https自签名证书，内网可访问，外网不行。该想的办法都想了，实在没法，提示页面见下。

“您请求的地址的连接已断开，出现这样的现场的原因可能有：
1. 在管理后台填的内网地址，在您的内网里本身已无法访问
2. 管理后台的 http 或 https 地址混用或填错
...........
”
怎么办？谢谢！

**Comment by billizpl** [comment]
![批注 2020-04-14 092957](https://user-images.githubusercontent.com/6510840/79176573-2bb5fb80-7e33-11ea-8fa5-0741d3493c89.png)

**Comment by billizpl** [comment]
http 80 没有问题，外网也能访问。

**Comment by billizpl** [comment]
难道只能用ddnsto的https,不能用自己的ssl吗？用ddnsto的证书，安全如何保证呀，只有无条件的相信吗？

**Comment by jannson** [comment]
你内网用需要把内网的地址设置为 https://xxx-你的内网地址：你的内网端口

这样是可以穿透的
