### ISSUE TITLE
需要点击左上角LOGO才能显示设备

### ISSUE THREAD

**Issue by DavidZhang73** [koolshare/ddnsto#12]
浏览器访问之后，弹窗，网络存在问题请重试。
显示此文件夹没有文件，点击左上角那个easyexplorer LOGO就可以正常访问了 不知道是软件的问题还是设置有问题

**Comment by jannson** [comment]
刚启动的时候，实际上有点慢，因为它要去找用户的其它设备，看状态，检测网络请求。等启动好了，就可以访问了。感谢反馈，请使用最新版本尝试。

**Comment by DavidZhang73** [comment]
已经好啦，谢谢大佬无私奉献
