### ISSUE TITLE
ddnsto错误信息

### ISSUE THREAD

**Issue by alujixiang** [koolshare/ddnsto#122]
![微信图片_20200611124114](https://user-images.githubusercontent.com/26339161/84345761-ca1acf00-abe0-11ea-9772-0582ffca8051.png)

**Comment by jannson** [comment]
一般来说是你的内网设备掉线了，或者你配置的网站无法访问了。

**Comment by alujixiang** [comment]
内网正常访问，添加挂载在路由器上面的优盘成功，打开提示连接失败。

发自我的iPhone
