### ISSUE TITLE
不能识别EXT4分区

### ISSUE THREAD

**Issue by wj36000** [koolshare/ddnsto#15]
R7000,7.7固件，USB3口接一个移动硬盘，分区格式为EXT4，安装插件后运行、连接正常，就是不能浏览分区内的内容。
PS：不过可以上传文件，显示不出来，但确实传进去了。

**Comment by wj36000** [comment]
补充一下，koolshare tomato固件软件中心未更新这个插件，是否能提供离线安装包？

**Comment by jannson** [comment]
好的，感谢提供。我们后面去确认下。最近还在弄其它东西。

**Comment by jannson** [comment]
大概定位到这个问题了，好像是文件权限导致的问题。

**Comment by wj36000** [comment]
请问宝哥这个问题会在后续版本修复吗？还是需要自己设置文件权限？

**Comment by jannson** [comment]
后面会修复，可能就最近几天就修复了。

**Comment by jannson** [comment]
这个问题应该修复了。
