### ISSUE TITLE
最新DSM 白群晖 EasyExplorer插件启动不起来

### ISSUE THREAD

**Issue by willembaby** [koolshare/ddnsto#18]
白群辉 设备型号：DS214PLAY
DSM版本 ：DSM 6.1.4-15217 Update 5
昵称：willembaby
故障问题：
手动安装好EasyExplorer插件，启动不起来了，没法使用。。。
请大神查看是否有问题

**Comment by jannson** [comment]
你能看到日志吗？可以直接用 http://你群辉的ip:8899/api/log 查看日志。贴给我，我定位下。

**Comment by jannson** [comment]
哦，我知道了。我家里也有一台 214 play。因为它是 arm 平台的，所以暂时不支持。现在支持的是 intel 平台的。我家里的 214play 坏了，新入手了 4 盘位的 intel 的，214 我还无法测试。
不过相信快了。

**Comment by willembaby** [comment]
多谢大神关注  希望能尽快支持214play，非常感谢

**Comment by delpyh** [comment]
我家的是ds214play，是intel atom ce5335的cpu，也是这个问题，服务无法启动。

请大神帮忙处理，谢谢了！

**Comment by delpyh** [comment]
> 哦，我知道了。我家里也有一台 214 play。因为它是 arm 平台的，所以暂时不支持。现在支持的是 intel 平台的。我家里的 214play 坏了，新入手了 4 盘位的 intel 的，214 我还无法测试。
> 不过相信快了。

请小宝兄弟关注一下，感谢。

**Comment by delpyh** [comment]
显示如下：
无法访问此网站 192.168.1.100 拒绝了我们的连接请求。
请在 Google 中搜索“192 168 100 8899”
ERR_CONNECTION_REFUSED

**Comment by jannson** [comment]
相关问题已经解决！
