### ISSUE TITLE
对文件容量的识别不准确

### ISSUE THREAD

**Issue by ojdev** [koolshare/ddnsto#19]
![_20180104225942](https://user-images.githubusercontent.com/2107833/34569239-21ddc3aa-f1a3-11e7-83d3-ae9d7b4cc005.png)
AC68U
CPU:ARMv7 Processor rev 0 (v7l)  -   (Cores: 2)
梅林:380.68_4-X7.7
EasyExplorer:插件版本：0.0.4
而且与DDNSto远程控制插件冲突，如果先运行了DDNSTO远程创建，且两个插件使用同一个token的话，easyexplorer会无法启动。

**Comment by jannson** [comment]
收到，我们会看看相关的 BUG
我也发现这个容量的问题了，在 windows 下是这样的，如果文件正在传输过程当中，则容量是不准确的。传输完成之后，就变正确了，请确认你的是否是这样的情况？

**Comment by MicahStudio** [comment]
不是传输的情况，好像是大文件。

**Comment by jannson** [comment]
收到，我们再看看。

**Comment by jannson** [comment]
应该是界面尺寸越界了。等换新 PC UI 之后再修复。

**Comment by jannson** [comment]
2.0 版本修复了此问题，请试试：https://github.com/koolshare/linkease
