### ISSUE TITLE
EasyExplorer插件安装后后，无法绑定路由器

### ISSUE THREAD

**Issue by error12306** [koolshare/ddnsto#20]
路由器型号：华硕AC68U
固件：梅林的7.7固件
问题：刷机完成，安装EasyExplorer插件根据提示获取token，但是注册成功www.ddns.to后，页面提示看起来您似乎还没有绑定过路由器：) 
您可以在 右上角查看您的 令牌 并复制到路由界面中用来启动插件”，
请问这个是什么原因？

我的信息如下：[url]www.ddns.to的注册用户名是[email]ysy0610@qq.com[/email][/url],路由器ID： （PID：2162）

**Comment by error12306** [comment]
卸载重新安装EasyExplorer插件之后，路由器id变成了27179

**Comment by jannson** [comment]
EasyExplorer 现在这个版本运行成功之后，管理后台并不会显示。

如果你要远程控制路由器界面，则用 ddns.to

如果你要相互共享，则在另外的设备也打开 EasyExplorer，就可以相互看见并共享。

**Comment by error12306** [comment]
@jannson 我希望在公司可以访问到家中路由器连接的移动硬盘共享文件，重新注册了ddns.to，还是提示未绑定路由器，方便邮箱跟你沟通具体的解决方案么？我的邮箱ysy0610@qq.com，谢谢

**Comment by RickyWong19922005** [comment]
問題一樣
R8500 
固件: koolshare v7.8
一直不能绑定

**Comment by jannson** [comment]
你的设备肯定是被别的用户给 绑定了。来 QQ 群联系管理员帮你删除相应的设备 ID
