### ISSUE TITLE
请教小宝老大。如何给手机安装 EasyExplorer 

### ISSUE THREAD

**Issue by w57759527** [koolshare/ddnsto#21]
我手机现在用ES文件管理器，也能发现网络上的设备，但是不能投屏。我的机顶盒能发现共享的文件夹，但是不能打开网络位置的文件。我路由器是斐讯的K3，换了闪存后，刷入了stones大神的lede，版本号是2.7.

**Comment by jannson** [comment]
我们正在开发手机端，目前还没有。
现在的版本也还是体验版本，没有任何 UI 设计的版本。

**Comment by w57759527** [comment]
谢谢宝大回复！在请教一下宝大，怎么实现机顶盒也能搜索到easyexplorer里面的内容，因为机顶盒支持dlan

**Comment by w57759527** [comment]
主要是因为机顶盒能搜到EasyExplorer的设备但是打开是空白，什么都没有。我用手机mediahouse也是能搜到EasyExplorer和通过Upnp分享的设备，但是EasyExplorer打开是空白,Upnp打开的正常。

**Comment by jannson** [comment]
不会吧，mediahouse 我打开是可以的啊。奇怪。能截图来瞧瞧么。要不今天晚上我更新一个版本吧，到时候看看。

**Comment by jannson** [comment]
最新版本试试。

**Comment by zzxxd** [comment]
能不能更改路径为C：/同步？
