### ISSUE TITLE
R7000梅林 7.7  想问下安装了 不会用，想卸载掉软件  不能卸载

### ISSUE THREAD

**Issue by fun665** [koolshare/ddnsto#22]
另外 在PC上共享的文件夹 怎么取消。。。

**Comment by jannson** [comment]
把插件关闭，就可以再卸载了。
PC 上共享的文件夹，把程序关了就可以取消了。

你的需求是，不想共享还是不想用此软件？

**Comment by fun665** [comment]
谢谢，已解决！

janson <notifications@github.com>于2018年1月30日 周二13:12写道：
