### ISSUE TITLE
官网AT外挂软件中心ddnsto无法运行

### ISSUE THREAD

**Issue by DavidZhang73** [koolshare/ddnsto#23]
以前用Koolshare改版tomato, 里面有一些自带的插件坏掉了， 比如TR，minidlna的目录设置， FTP的用户设置，所以换成原版+外挂软件中心， 但是ddnsto显示
`ddnsto进程未运行！`
到后台检查发现
`<p>root@xxx:/tmp/home/root# ddnsto</p><p>cat: can't open '/etc/openwrt_release': No such file or directory</p><p>init error</p>`

**Comment by jannson** [comment]
目前外挂软件中心暂时不支持，到以后才会修复。
