### ISSUE TITLE
无法访问,请老大赐教

### ISSUE THREAD

**Issue by HHHHN** [koolshare/ddnsto#25]
您请求的地址的连接已断开，出现这样的现场的原因可能有：
    1. 在管理后台填的内网地址，在您的内网里本身已无法访问
    2. 管理后台的 http 或 https 地址混用或填错
    3. 您的设备连接未知原因已下线，请在管理后台确认您的设备是否还在线（有亮色并有连接速度显示表示还在线）
    4. 若还无法解决你的问题，请到 DDNSTO Github 地址 反馈您的问题
    5. 论坛问题反馈地址 KoolShare 论坛

    以下情况可能会导致短暂的访问错误，请等待 10 秒 ~ 50 秒左右
    * 刚添加或删除了新的子域名
    * 您的设备在内网里的公网 ip 产生了变化

**Comment by jannson** [comment]
按　１　２　３　步骤试了吗？看看你后台的数据是什么样子的。

**Comment by orrzz** [comment]
> 总上传
3.9 KB
总下载
120 bytes
当日上传
3.9 KB
当日下载
120 bytes
当前上传速度
0 bytes / s
当前下载速度
0 bytes / s

进程运行正常！版本：0.2.1 

Jun  4 22:55:00 crond[588]: USER admin pid 8040 cmd /koolshare/scripts/ddnsto_check.sh
Jun  4 22:55:03 dropbear[8073]: Child connection from 58.229.175.126:53181
Jun  4 22:55:04 dropbear[8073]: Login attempt for nonexistent user from 58.229.175.126:53181
Jun  4 22:55:04 dropbear[8073]: Exit before auth: Disconnect received
Jun  4 22:57:12 ddnsto[8239]: client init ok username=10ffbdba------------------------------------1332 routerId=----------------88 version=0.2.1
Jun  4 22:58:19 ddnsto[8239]: main accept error count=0 wait_cnt=0
Jun  4 22:58:19 ddnsto[8237]: check reboot failed, ret=-1
Jun  4 22:58:42 ddnsto[8366]: client init ok username=10ffbdba------------------------------------1332 routerId=----------------88 version=0.2.1
Jun  4 22:59:24 ddnsto[8366]: cannot connect to private network

**Comment by jannson** [comment]
从日志看，是你填写的你的内网地址错误，请再确认下。
Jun 4 22:59:24 ddnsto[8366]: cannot connect to private network
是你的配置问题。

**Comment by 545433836** [comment]
我的梅林固件在ddns注册花生壳局域名后也出现同样的提示问题，后来又删除了我注册DDNSTO的设备，准备重新配置，结果找不到服务器了，不能重新设置，请问怎么样解决？
