### ISSUE TITLE
请教老大，最新DSM 白群晖 EasyExplorer插件无法手动安装

### ISSUE THREAD

**Issue by tianhuanyun** [koolshare/ddnsto#27]
白群辉 设备型号：DS218+
处理器型号：Intel Celeron J3355
DSM版本 ：DSM 6.1.5-15254
昵称：tianhuanyun
故障问题：
无法手动安装EasyExplorer插件，提示“该套件不支持 DiskStation 上的平台，或与当前版本的DSM不兼容，求教大神如何处理？
谢谢大神了

**Comment by kingswon** [comment]
同样问题    DS718+   J3455

**Comment by jannson** [comment]
相关问题应该都已经解决。
