### ISSUE TITLE
实测DLNA无效，无法推送列表

### ISSUE THREAD

**Issue by kero990** [koolshare/ddnsto#33]
电脑端easyexplorer，ios端用nplayer，playerxtreme，android端splayer等播放器，结果均一样，能搜到dlna服务器，但点进去没有任何推送，空文件夹。我的目录有mp4,avi和mkv的。

是我网络的问题吗，可我换父母家电信+梅林的ee也是一样的

是我dlna用得不对，还是目前dlna还不完美？

另外，ee的操作界面，在移动端浏览器中，右下角有个操作按钮，但pc浏览器没有，我搞不懂怎么弄出右键菜单那个效果来。。。

**Comment by jannson** [comment]
pc 浏览器里面，你右键，就出来右键的那个菜单了啊。
同时现在　iOS 不建议使用　dlna 了，直接用　vlc 可以在浏览器里播放。自动打开　vlc 软件界面来放视频。
DLNA 我测试一直是好的，我也不太理解你的为何不行。

**Comment by jannson** [comment]
不过现在还是体验版本。未来 app 端应该是会有　app 的。

**Comment by kkkkyue** [comment]
确实是只能搜索到服务器 但
![snipaste20180607_231157](https://user-images.githubusercontent.com/6251448/41108859-353d8268-6aa8-11e8-973c-f1ba646dca4a.png)
是目录是看不到的。8200端口。没有任何数据。

**Comment by kero990** [comment]
@jannson 
浏览器里右键我出来的可是浏览器的右键菜单啊，chrome
dlna不能用的那个，我至少试了2台电脑用pc版本，1个路由器版本，n种播放器都一样，只能看见服务器，进去没有任何文件列表推送

**Comment by jannson** [comment]
sorry，后来思考，为了更简化体验，最近正在开发 APP 版本来满足大家的需求，所以 DLNA 与 video_mux 都干掉了。
EasyExplorer 的目标是注重简单，APP 最简单。
