### ISSUE TITLE
近期经常无法连接到路由器

### ISSUE THREAD

**Issue by icetea0822** [koolshare/ddnsto#34]
期间什么设置都没有改过，突然就不行了，之前有过一次，然后恢复出厂设置重新安装插件才好，这次用了不到一个礼拜就不行了，日志一直显示：
Mar 22 14:45:14 ddnsto[9688]: dial ipv4 failed retry=3 remote=tunnel.ddns.to:4445
Mar 22 14:45:36 ddnsto[9688]: failed   ! mbedtls_ssl_handshake returned -0x50
Mar 22 14:45:36 ddnsto[9688]: dial ipv4 failed retry=4 remote=tunnel.ddns.to:4445
Mar 22 14:45:49 ddnsto[9688]: dial ipv4 failed retry=5 remote=tunnel.ddns.to:4445
Mar 22 14:46:04 ddnsto[9688]: dial ipv4 failed retry=6 remote=tunnel.ddns.to:4445
Mar 22 14:46:21 ddnsto[9688]: dial ipv4 failed retry=7 remote=tunnel.ddns.to:4445
Mar 22 14:46:21 ddnsto[2017]: check reboot failed, ret=-1
Mar 22 14:46:54 ddnsto[9807]: dial ipv4 failed retry=1 remote=tunnel.ddns.to:4445
Mar 22 14:47:01 ddnsto[9807]: dial ipv4 failed retry=2 remote=tunnel.ddns.to:4445
Mar 22 14:47:10 ddnsto[9807]: dial ipv4 failed retry=3 remote=tunnel.ddns.to:4445
Mar 22 14:47:21 ddnsto[9807]: dial ipv4 failed retry=4 remote=tunnel.ddns.to:4445
Mar 22 14:47:34 ddnsto[9807]: dial ipv4 failed retry=5 remote=tunnel.ddns.to:4445
Mar 22 14:47:49 ddnsto[9807]: dial ipv4 failed retry=6 remote=tunnel.ddns.to:4445
Mar 22 14:48:06 ddnsto[9807]: dial ipv4 failed retry=7 remote=tunnel.ddns.to:4445
Mar 22 14:48:06 ddnsto[2017]: check reboot failed, ret=-1
请问是什么原因呢，路由器是没问题可以正常使用的。

**Comment by Jiangtaste** [comment]
同样情况，远程访问直接报503

**Comment by ghkghkghk** [comment]
同样的情况，路由器其他功能一切正常。
设备：华为WS880
系统：梅林7.8
插件：ddnsto

**Comment by jannson** [comment]
这种问题，估计是服务器与你家的网络连接性不是特别好。因为时间太久我先关闭 BUG，有问题再来反馈。
