### ISSUE TITLE
提交之后，插件又变回关闭状态了

### ISSUE THREAD

**Issue by StephenMMMMM** [koolshare/ddnsto#36]
把Token复制到插件里面，然后打开插件提交之后，插件就默认关闭了
运行状态是：【警告】：进程未运行！ 版本：0.2.1 路由器ID：c0ffd49703cd 
固件版本：380.66_4-X7.5 
软件中心版本：1.3.4

**Comment by KinsonSiu** [comment]
我也是，86U

**Comment by jannson** [comment]
插件修改了，现在好了吗？

**Comment by StephenMMMMM** [comment]
在2.9.1版本验证该问题，插件可正常使用，非常感谢！！

janson <notifications@github.com> 于2018年12月9日周日 下午9:50写道：
