### ISSUE TITLE
k3梅林刷机后easyExplorer路由器ID还是刷机前的，没有跟着变更过来

### ISSUE THREAD

**Issue by xiangme** [koolshare/ddnsto#37]
第一次使用很好，后面刷了一次机，使用混血梅林，路由器ID变更了，但是easyExplorer插件里，还是显示原来的刷机前路由器ID，导致无法访问！
DDNS注册ID：xiangme
请小宝大大帮忙修改下！

**Comment by jannson** [comment]
不好意思，前段时间太忙了。你现在的好用了吗？
