### ISSUE TITLE
ddnsto登陆问题

### ISSUE THREAD

**Issue by mf1362956793** [koolshare/ddnsto#46]
最近发现使用www.ddnsto.com/#/login     这个网址登陆账号和密码都检查过还重设过（之前用的微信登陆），按照koolshare上面获得的账号，但就是无法登陆，密码重设了好多次！
账号：o220M1UujEG6L2vs1yW-yFT8QbmI

**Comment by jannson** [comment]
你现在还能用微信登录吗？

**Comment by jannson** [comment]
一般性 BUG 在这里反馈，如果是登录这种，建议从官网找到 qq 群，进去咨询。

**Comment by mf1362956793** [comment]
> 一般性 BUG 在这里反馈，如果是登录这种，建议从官网找到 qq 群，进去咨询。

现在恢复了，前天又怀着好奇试了一下
