### ISSUE TITLE
ping ddnsto.com 故障 10秒超时多次  请开发人员看一下 是什么情况哈

### ISSUE THREAD

**Issue by csx43600121** [koolshare/ddnsto#48]
ping ddnsto.com 故障 10秒超时多次  请开发人员看一下 是什么情况哈

![_20190126180600](https://user-images.githubusercontent.com/7018803/51785599-15bc0c80-2195-11e9-9fb6-cc1223569555.png)

**Comment by jannson** [comment]
现在好了吧？亲。

**Comment by jannson** [comment]
ping www.ddnsto.com
PING www.ddnsto.com (60.214.107.49) 56(84) bytes of data.
64 bytes from 60.214.107.49: icmp_seq=1 ttl=49 time=44.3 ms
64 bytes from 60.214.107.49: icmp_seq=2 ttl=49 time=44.6 ms
64 bytes from 60.214.107.49: icmp_seq=3 ttl=49 time=42.7 ms
64 bytes from 60.214.107.49: icmp_seq=4 ttl=49 time=117 ms
64 bytes from 60.214.107.49: icmp_seq=5 ttl=49 time=106 ms
64 bytes from 60.214.107.49: icmp_seq=6 ttl=49 time=66.7 ms
64 bytes from 60.214.107.49: icmp_seq=7 ttl=49 time=42.8 ms
64 bytes from 60.214.107.49: icmp_seq=8 ttl=49 time=47.3 ms
64 bytes from 60.214.107.49: icmp_seq=9 ttl=49 time=46.3 ms
64 bytes from 60.214.107.49: icmp_seq=10 ttl=49 time=53.2 ms
64 bytes from 60.214.107.49: icmp_seq=11 ttl=49 time=45.1 ms
64 bytes from 60.214.107.49: icmp_seq=12 ttl=49 time=91.9 ms

**Comment by csx43600121** [comment]
现在好了  感谢！！
