### ISSUE TITLE
DDNSTO别人访问要验证

### ISSUE THREAD

**Issue by alegoho** [koolshare/ddnsto#49]
我在DDNSTO上做了内网穿透，我自己访问没问题，可以把地址发给别人的访问时要验证，弹了个二维码出来，请问这个内网穿透只能自己用的吗？

**Comment by jannson** [comment]
目前是这样子的，只能自己用。给别人用会有其它安全风险！

**Comment by aa51513** [comment]
我在内网上存放一些非隐私的文件，想共享给他人，也要验证；使用起来非常的麻烦，这个验证有地方可以关闭吗？
