### ISSUE TITLE
更新到最新版后无法通过浏览器访问

### ISSUE THREAD

**Issue by zxtp1981** [koolshare/ddnsto#55]
更新到最新版后通过浏览器打开127.0.0.1:8899，提示“网络存在问题，请重试”。路由器插件版本“0.0.10”，主程序：“0.1.28”及电脑端已更新至20190417.051642“Easy-explorer-x86”。更新前可以正常访问

设备型号ASUS RT-AC1750 B1无线路由器，固件刷的梅林380.70_0-X7.9.1，软件中心版本1.4.4，插件通过软件中心直接更新。

Koolshare Asuswrt-Merlin EasyExplorer Changelog
===========================================
0.0.10 ( 2019-04-17 )
  - Update    更新主程序20190417.051642
0.0.9 ( 2018-12-09 )
  - Update    更新主程序20181209.033820
0.0.8 ( 2018-09-21 19:50 )
  - Update    更新主程序，提升传输效率
0.0.7 ( 2018-09-13 19:30 )
  - Update    更新主程序
0.0.6 ( 2018-09-11 20:40 )
  - Update    更新主程序
0.0.5 ( 2018-05-28 11:00 )
  - Update    更新主程序
0.0.4 ( 2017-12-28 11:00 )
  - Add       增加时间同步功能
0.0.3 ( 2017-12-22 13:50 )
  - Fix       优化安装脚本
0.0.2 ( 2017-12-22 12:50 )
  - Add       增加插件NAT-START启动
  - Fix       开放EasyExplorer防火墙加密端口，用于外网TCP传输
0.0.1 ( 2017-12-19 22:00 )
  - Add       第一个预览版

**Comment by jannson** [comment]
在 /tmp/easy-explorer.log 
里面看看，有没有相关的日志。
或者在 /koolshare/bin 目录里，手动运行下程序，看是否能运行成功
cd /koolshare/bin
./easy-explorer

**Comment by zxtp1981** [comment]
日志如下：
2019/04/22 08:39:17 Using stun address= 221.229.175.68:3478 RemoteAddr= tunnel.ddnsto.com:4445
2019/04/22 08:39:17 client init ok, connecting to server
2019/04/22 08:39:20 regist ok
2019/04/22 08:39:20 connected to server
2019/04/22 08:39:22 discovering nat type, please wait...
2019/04/22 08:39:41 NAT Type: Unexpected response from the STUN server host 86.98.32.42:56004
2019/04/22 08:39:52 New NAT port mapping: external TCP address 86.98.32.42:36906 to local address 192.168.0.160:2300
2019/04/22 08:39:52 Detected 1 NAT device
2019/04/22 08:39:52 update tcp mapping old=  new= 86.98.32.42:36906  extIP= 86.98.32.42
2019/04/22 08:40:01 tcp nat error, upnp addr 86.98.32.42:36906 not in public

**Comment by jannson** [comment]
说明你运行 是成功的。最近我发现启用了 mac clone 进行拨号的，会有问题。

**Comment by jannson** [comment]
这个问题已经解决。用新的方式来生成设备 ID，mac clone 不会再有问题。
