### ISSUE TITLE
#黑群晖#群晖dsm输入目录不存在，群晖目录应该怎么选取

### ISSUE THREAD

**Issue by sugertanyong** [koolshare/ddnsto#62]
#黑群晖#群晖dsm输入目录不存在，群晖目录应该怎么选取

**Comment by jannson** [comment]
目前的办法是，手动在 dsm 里面找一个目录，然后去选择。
7 天内会实现一个版本，可以在网页选择 nas 里面的目录的功能，到时候更新了我会来关闭这个 issue。
感谢支持。

**Comment by jannson** [comment]
新版本 0.1.31 支持在配置界面选择目录了！
