### ISSUE TITLE
运行后打开管理页面提示

### ISSUE THREAD

**Issue by gcbzq32l** [koolshare/ddnsto#64]
{"code":"40510001","msg":"invisible bucket"}

**Comment by QianParker** [comment]
I have the same issue.
{"code":"40510001","msg":"invisible bucket"}

**Comment by sadoneli** [comment]
请将易有云版本更新至最新

**Comment by jannson** [comment]
因为我的失误，有一个域名不对，导致 cdn 出问题。更新最新版本可以解决。
