### ISSUE TITLE
#iOS# 支持批量下载到相册当中去

### ISSUE THREAD

**Issue by jannson** [koolshare/ddnsto#71]
支持批量下载到相册当中去。

**Comment by YGAS** [comment]
怎么批量保存图片到手机吗？其实现在就可以，远程我是故意限制了分享的功能的。因为远程的文件必须经过下载才能调用分享，所以我限制了5M以内的文件才能分享，不然在实际使用过程中会等待过长。

**Comment by YGAS** [comment]
现在的做法是，第一步，把电脑上的照片批量复制到手机端，第二步，手机端多选照片然后点分享

**Comment by YGAS** [comment]
![149F119A44E021BFA81629AC793DA618](https://user-images.githubusercontent.com/1214708/59344352-7f057c00-8d40-11e9-834d-2b8d2b91673a.png)
