### ISSUE TITLE
IOS怎么登陆啊？

### ISSUE THREAD

**Issue by Tasty-Warning** [koolshare/ddnsto#73]
输入了手机号，然后短信发来了一串代码，复制到浏览器里没用啊

**Comment by jannson** [comment]
你手机上，没有微信是吧？
是用微信登录的。如果没有微信，会出来一个网页，估计是要你注册微信了。

**Comment by jannson** [comment]
确认是没有微信导致，可以在 https://www.ddnsto.com 设置自己的邮箱与密码。
