### ISSUE TITLE
Mac OS客户端打开提示需要联系开发者更新

### ISSUE THREAD

**Issue by ztz1022** [koolshare/ddnsto#80]
机型：Macbook pro-2018 13寸
下载完易有云Mac OS客户端后，出现如图提示。
<img width="418" alt="Screen Shot 2019-07-19 at 9 21 37 AM" src="https://user-images.githubusercontent.com/52316047/61550231-c994ab00-aa06-11e9-8a4d-672f7ec70284.png">

**Comment by ztz1022** [comment]
系统：10.14.5

**Comment by jannson** [comment]
这个表苹果最新版本出来的问题，我升级系统之后， 也被这个问题困扰好久。
后面我一顿操作，在 elfinder 里面右键可以打开，解压之后， 把程序复制到 Applications 下面，就好了。

我也是从　github　一个　issue 学来的，我现在找不到，找到再补充。

**Comment by jannson** [comment]
https://github.com/electron-userland/electron-builder/issues/3870

https://github.com/univ-of-utah-marriott-library-apple/display_manager/issues/13

等我有空看如何修复下。上次我没注意，也不太记得解决的细节了。
