### ISSUE TITLE
主路由梅林安装了易有云，是否能把体现下面的设备下载宝的SMB、NFS、FTP？

### ISSUE THREAD

**Issue by qq495679584** [koolshare/ddnsto#81]
主路由梅林安装了易有云，是否能把体现下面的设备下载宝的SMB、NFS、FTP？

**Comment by jannson** [comment]
如果是 NAS 还有可能，但是路由器性能不够，搞这么肯定跑不起来。

半年内还没有这个计划，技术上 NAS 是可以办到的。
