### ISSUE TITLE
DDNSTO开源

### ISSUE THREAD

**Issue by ityc** [koolshare/ddnsto#83]
你好ddnsto非常好用,但由于我所在的网络比较特殊,所以想咨询ddnsto是否开源,如果闭源有没有授权,目前只能找到打包好的程序,所以来咨询下.

**Comment by jannson** [comment]
ddnsto 是一个闭源产品，开源的有 ngrok 与 frp，你可以找找看。

ddnsto 相比 ngrok 肯定好很多

ddnsto 在嵌入式环境下应该比其它同类产品好。在其它环境下我没有很详细的比较。如果对 ddnsto 商业应用有兴趣可以加我们群 QQ 聊。
