### ISSUE TITLE
群晖无法打开

### ISSUE THREAD

**Issue by sunshineyxc** [koolshare/ddnsto#88]
群晖安装易有云插件后，群晖控制页面无法打开。

硬件：Intel(R) Celeron(R) CPU 3215U @ 1.70GHz 
安装了ESXI，上面有个虚拟群晖，安装插件后，页面无法显示
![QQ截图20190909200428](https://user-images.githubusercontent.com/55090291/64529251-0d3bcf00-d33d-11e9-8a7f-024efdf95831.png)

**Comment by jannson** [comment]
2.0 版本： https://github.com/koolshare/linkease
这个 OK 了。
