### ISSUE TITLE
mac版的易有云如何切换token？使用微信登录的

### ISSUE THREAD

**Issue by Mrycp** [koolshare/ddnsto#94]
mac版的已有云如何切换token？使用微信登录的

**Comment by Han-Orz** [comment]
找到用户目录下 ~/EasyExplorer/config.json 文件
里面的username后跟的就是token，改完保存，然后重新启动易有云就可以了

**Comment by Mrycp** [comment]
> 找到用户目录下 ~/EasyExplorer/config.json 文件
> 里面的 username 后跟的就是 token，改完保存，然后重新启动易有云就可以了。

感谢解答，虽然之前通过查看接口找到了配置文件并且修改成功了。

**Comment by jannson** [comment]
感谢回复。
