### ISSUE TITLE
请教关于arris 3200p路由器ddnsto

### ISSUE THREAD

**Issue by xuruarua** [koolshare/ddnsto#96]
你好，请问是小宝大神吗？我在淘宝午饭家买的arris3200p路由器，了解到改版固件是你写的，技术支持也是你在做。今天刚刚更新了b5的固件，软件中心正常工作了，感谢你的最新修改，这个软件中心bug是我月初与淘宝午饭家沟通提出，再次感谢你的修改。  ……         现在的问题是，ddnsto在软件中心下载不到，我在github上下载的虽然能装上，但是无法运行，显示进程未运行……读取不到路由器ID，提示可以更新到2.9.2……但是在线软件中心没有此插件。设备cpu型号：ARMv7 Processor rev 0 (v7l) 。也尝试了更早期版本的ddnsto，直接就无法进入界面。与午饭家沟通无果，仍然头疼中。冒昧打扰了。如能解答，不胜感激。

**Comment by sadoneli** [comment]
我来回答下，ddnsto服务目前是免费的，目前免费提供给koolshare开发组开发的固件使用。其它非koolshare开发的固件，暂时没有提供支持的。

**Comment by xuruarua** [comment]
那想用这个功能估计只能换路由器了，呃呃呃呃
