### ISSUE TITLE
威联通532X无法打开易有云

### ISSUE THREAD

**Issue by jackyhsu88** [koolshare/ddnsto#97]
![TIM截图20191124105628](https://user-images.githubusercontent.com/58127079/69489032-ddb55100-0ead-11ea-9014-ee6d18eb4e24.png)
![02](https://user-images.githubusercontent.com/58127079/69489033-e0b04180-0ead-11ea-9af6-d3bd77965969.png)

**Comment by jannson** [comment]
https://github.com/koolshare/linkease

请使用易有云 2.0 版本。
