### ISSUE TITLE
关于易有云的登陆

### ISSUE THREAD

**Issue by Sam-Paul** [koolshare/ddnsto#98]
使用上一切都正常,有一个问题困扰
在公司上班打开易有云之后,因为公司电脑可能有其他人使用,一旦他人打开易有云,也可以对其进行文件的操作,可否设置成每次登陆易有云都验证账号信息呢?谢谢

**Comment by jannson** [comment]
后来我加了一个本地授权，只给本地电脑使用的功能。

大版本开发中，这个功能已经包含在里面。

**Comment by jannson** [comment]
https://github.com/koolshare/linkease

2.0 版本解决了这个问题，谢谢。
